/*
 * Uber API
 *
 * Move your app forward with the Uber API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/mux"
)

type Secret struct {
	SecretText string
	Hash       string
	ViewTime   int
	ExpiredAt  time.Time
	CreatedAt  time.Time
}

func main() {
	router := mux.NewRouter().StrictSlash(true)
	router.HandleFunc("/secret", SecretCreate)
	router.HandleFunc("/secret/{hash}", SecretGet)

	log.Fatal(http.ListenAndServe(":8080", router))
}
func SecretCreate(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "Welcome!")
}

func SecretGet(w http.ResponseWriter, r *http.Request) {
	secret := Secret{
		SecretText: "hello",
		Hash:       "1231231",
		ViewTime:   4,
		ExpiredAt:  time.Now(),
	}

	json.NewEncoder(w).Encode(secret)
}
